//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequestApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestTable
    {
        public int ID_Request { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string RequestDateArrival { get; set; }
        public string RequestRegistered { get; set; }
        public string RequestFinished { get; set; }
        public string DocumentName { get; set; }
        public string DocumentContent { get; set; }
    }
}
